In [2]:
!pip install pymongo

Collecting pymongo
  Downloading pymongo-4.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.6.1-py3-none-any.whl.metadata (5.8 kB)
Downloading pymongo-4.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (669 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.0/670.0 kB 14.6 MB/s eta 0:00:00a 0:00:01
Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 53.3 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.6.1 pymongo-4.7.1

In [1]:
import pymongo
import pandas as pd

# Replace the connection string with your MongoDB deployment URI
connection_string = 'mongodb://talentedge:talentedge@10.0.110.212:27017/talentedge?retryWrites=true&w=majority'

# Establish connection to MongoDB
client = pymongo.MongoClient(connection_string)

# Access a specific database, replace 'your_database' with your actual database name
db = client['talentedge']

# Access a specific collection in the database, replace 'your_collection' with your actual collection name
collection = db['requisitionYearlyDump']


# data = pd.DataFrame(list(collection.find({"location.state" : "NY"})))
# data


# Get the data by job title

query = { "title": "Data Scientist" }
data = pd.DataFrame(list(collection.find(query)))
data


# Get first x data items from a query

# # Retrieve 10 records from the collection
# cursor = collection.find(query) #.limit(10)
# # Iterate over the cursor to print the documents
# for document in cursor:
#     print(document)

# # Close the connection when done
# client.close()

,_id,requiredSkills,requiredQualifications,title,requisitionId,jobLevel,jobCategory,jobSpecialty,jobType,jobClassification,...,status,openPositions,postingDate,closingDate,recruiterId,hiringManagerId,shift,requisitionReason,effectiveStartDate,effectiveEndDate
0,660fa38ce9e7718894ea99bf,"[Artificial Intelligence, Computer Skills, Sof...",[],Data Scientist,823218882436188,None,Data Scientist,,Professional,222.776442,...,open,,2024-03-28,NaT,,,,Project Expansion,2024-03-28,
1,660fa38ce9e7718894ea9a52,"[statistical modeling, web application develop...",[],Data Scientist,823218882439576,None,Data Scientist,,Professional,63.701923,...,open,,2024-03-28,NaT,,,,Project Expansion,2024-03-28,
2,660fa38ce9e7718894eaa968,[statistical modeling],[],Data Scientist,823218882435977,None,Data Scientist,,Professional,66.562500,...,pending close,,2024-03-28,2024-03-31 02:33:27,,,,Project Expansion,2024-03-28,
3,660fa38ce9e7718894eaaf39,[],[],Data Scientist,823218882483703,None,Data Scientist,,Professional,97.355769,...,pending close,,2024-03-28,2024-03-29 21:26:44,,,,Project Expansion,2024-03-28,
4,660fa38ce9e7718894eabdeb,[Data As A Service],[],Data Scientist,823218882345378,None,Data Scientist,,Professional,34.375000,...,open,,2024-03-27,NaT,,,,Project Expansion,2024-03-27,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5041,661d77e6d7c0a99755f122b6,"[Analytics, Research, api, fast-paced]",[Python],Data Scientist,823218828539812,None,Data Scientist,,Professional,55.380288,...,closed,,2023-05-13,2023-06-09 16:24:39,,,,Project Expansion,2023-05-13,
5042,661d7838d7c0a99755f178a0,"[Ability To Learn, Analytical, Analytics, Anal...","[ERP, Excel, Google Cloud Platform, MS Excel, ...",Data Scientist,823218828499629,None,Data Scientist,,Professional,63.634135,...,closed,,2023-05-13,2023-06-09 17:00:58,,,,Project Expansion,2023-05-13,
5043,661d793bd7c0a99755f2510d,"[Analytics, Attention To Detail, Compliance, C...","[Python, google+]",Data Scientist,823218828659812,None,Data Scientist,,Professional,51.272596,...,closed,,2023-05-13,2023-05-21 04:49:20,,,,Project Expansion,2023-05-13,
5044,661d793bd7c0a99755f27462,"[Artificial Intelligence, Augmented Reality, B...","[MS Office, OS X, ms visio]",Data Scientist,823218828513443,None,Data Scientist,,Professional,47.829808,...,closed,,2023-05-13,2023-06-20 03:49:42,,,,Project Expansion,2023-05-13,
5045,661d79ead7c0a99755f30bd6,"[Ability To Learn, Analytical, Analytics, Anal...","[ERP, Excel, Google Cloud Platform, MS Excel, ...",Data Scientist,823218828499629,None,Data Scientist,,Professional,63.634135,...,closed,,2023-05-13,2023-06-09 17:00:58,,,,Project Expansion,2023-05-13,

In [3]:
#len(cursor)